### ISSUE TITLE
yarn create fusion-app my-fusion-app - internal/util.js:206     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');

### ISSUE THREAD

**Issue by mobicycle** [fusionjs/create-fusion-app#37]
cabox@box-codeanywhere:~/workspace$ yarn create fusion-app mytestapp
yarn create v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-fusion-app@0.0.3" with binaries:
      - create-fusion-app
[#####################################################################################################################################] 319/319internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (/home/cabox/.config/yarn/global/node_modules/fusion-scaffolder/index.js:17:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cabox/.config/yarn/global/node_modules/create-fusion-app/bin/cli.js:8:18)
error Command failed.
Exit code: 1
Command: /home/cabox/.yarn/bin/create-fusion-app
Arguments: mytestapp
Directory: /home/cabox/workspace
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by KevinGrandon** [comment]
Hello, thanks for filing an issue. I believe we talked about this on Slack and it seemed that the node version you were using was quite old (0.x). Please try upgrading to node 8.11.3 and see if it still reproduces. Feel free to comment here, or open a new issue. Thanks!
