### ISSUE TITLE
Windows 10 Enterprise - yarn dev - Error: Cannot find module

### ISSUE THREAD

**Issue by alexstaroselsky** [fusionjs/create-fusion-app#45]
Hello!

I first off want to thank you for creating this amazing set of tools and plugins.

I'm receiving an error when trying to run `yarn dev` on Windows 10 Enterprise with Yarn 1.9.4. The app was created using `yarn create fusion-app fusion`:

```
Error: Cannot find module 'C:UserssomeuserDocumentsTestusion
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\someuser\Documents\Test\fusion\.fusion\dist\development\server\server-main.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

It looks like the module is attempting to be located without slashes in the path. It also is treating lowercase "f" character in "fusion" as a special character of some sort. It seems to maybe even be removing critical characters in the path. When I create a project using command `yarn create fusion-app baz`, the following error occurs when executing `yarn dev`. The project was named "baz", but you can see in the first part of the error that the last "t" of "Test" and the "b" of "baz" is missing:

```
Error: Cannot find module 'C:UserssomeuserDocumentsTesaz
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\someuser\Documents\Test\baz\.fusion\dist\development\server\server-main.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Here is the system information just in case:

OS Name:	Microsoft Windows 10 Enterprise	
Version: 	        10.0.14393 Build 14393		
System Type:	x64-based PC	
Processor:	Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2904 Mhz, 2 Core(s), 4 Logical Processor(s)

All that being said, `yarn build` executes without error, but running `yarn start` after a successful `yarn build`:

```
$ fusion start
C:\Users\someuser\Documents\Test\baz\node_modules\fusion-cli\bin\cli-runner.js:12
  throw e;
  ^

Error: Cannot find module 'C:UserssomeuserDocumentsTesaz
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\someuser\Documents\Test\baz\.fusion\dist\development\server\server-main.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
```

I'm able to create and run other node based projects such as `create-react-app`, `@angular/cli` and `@vue/cli` without issue on this machine using both yarn and npm/npx.

Thank you for any assistance you can provide.

**Comment by KevinGrandon** [comment]
Thank you for filing the issue and sorry for the problems you're experiencing. Right now on windows we're recommending using Docker for development and you can find more information in the following issue:  https://github.com/fusionjs/fusion-cli/issues/461#issuecomment-411294134

Happy to help get this setup if you run into problems.
