### ISSUE TITLE
Scaffolded fusion-app will not build

### ISSUE THREAD

**Issue by jasonbarone** [fusionjs/create-fusion-app#71]
## Current Behavior
After scaffolding a new fusion-app using yarn create, the fusion-app will not build correctly and returns the following error:

```
$ fusion build
(node:96929) Warning: N-API is an experimental feature and could change at any time.
(node:96929) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Build completed in 4.82s

Build completed in 4.812s

error: (client) /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/client-entry.js
Module not found: Error: Can't resolve 'fusion-core' in '/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries'
resolve 'fusion-core' in '/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries'
  Parsed request is a module
  using description file: /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/package.json (relative path: ./entries)
    Field 'browser' doesn't contain a valid alias configuration
    Field 'es2015' doesn't contain a valid alias configuration
    Field 'es2017' doesn't contain a valid alias configuration
    resolve as module
      /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/node_modules doesn't exist or is not a directory
      /Users/jasonbarone/.config/yarn/global/node_modules/node_modules doesn't exist or is not a directory
      /Users/jasonbarone/.config/yarn/node_modules doesn't exist or is not a directory
      /Users/jasonbarone/.config/node_modules doesn't exist or is not a directory
      /Users/jasonbarone/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules
        using description file: /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          Field 'es2015' doesn't contain a valid alias configuration
          Field 'es2017' doesn't contain a valid alias configuration
      looking for modules in /Users/jasonbarone/.config/yarn/global/node_modules
        using description file: /Users/jasonbarone/.config/yarn/global/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          Field 'es2015' doesn't contain a valid alias configuration
          Field 'es2017' doesn't contain a valid alias configuration
          using description file: /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/package.json (relative path: ./node_modules/fusion-core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
          using description file: /Users/jasonbarone/.config/yarn/global/package.json (relative path: ./node_modules/fusion-core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              Field 'es2015' doesn't contain a valid alias configuration
              Field 'es2017' doesn't contain a valid alias configuration
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.json doesn't exist
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.json doesn't exist
            as directory
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core doesn't exist
            as directory
              /Users/jasonbarone/.config/yarn/global/node_modules/fusion-core doesn't exist
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/node_modules]
[/Users/jasonbarone/.config/yarn/global/node_modules/node_modules]
[/Users/jasonbarone/.config/yarn/node_modules]
[/Users/jasonbarone/.config/node_modules]
[/Users/jasonbarone/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-core]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.wasm]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.wasm]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.mjs]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.mjs]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.js]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.js]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/fusion-core.json]
[/Users/jasonbarone/.config/yarn/global/node_modules/fusion-core.json]
 @ /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/client-entry.js 12:0-61 26:6-18 28:23-39 31:19-35
 @ multi /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/client-public-path.js /Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/entries/client-entry.js
/Users/jasonbarone/.config/yarn/global/node_modules/@gfx/zopfli/dist/libzopfli.js:1
(function (exports, require, module, __filename, __dirname) { var Module=typeof Module!=="undefined"?Module:{};const base64=require("base64-js");const base64EncodedBinary=require("./libzopfli-wasm");var Module={};Module.noInitialRun=true;Module.wasmBinary=base64.toByteArray(base64EncodedBinary);var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENV

Error: Compiler stats included errors.
    at compiler.start (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/commands/build.js:43:30)
    at handler (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/build/compiler.js:152:9)
    at finalCallback (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/Users/jasonbarone/.config/yarn/global/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jasonbarone/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jasonbarone/.config/yarn/global/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:371:39)
    at emitAssets.err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/Users/jasonbarone/.config/yarn/global/node_modules/fusion-cli/node_modules/webpack/lib/Compiler.js:357:14)
```

## Expected Behavior
Fusion app should build.

## Versions
```
    "fusion-cli": "^1.16.0",
    "fusion-core": "^1.10.3",
    "fusion-plugin-react-helmet-async": "^1.0.2",
    "fusion-plugin-react-router": "^1.5.1",
    "fusion-plugin-styletron-react": "^2.5.4",
    "fusion-plugin-universal-events": "^1.3.2",
    "fusion-react": "^1.3.7",
    "fusion-tokens": "^1.1.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "styletron-react": "^4.4.4"
```

**Comment by chrisdothtml** [comment]
Looks like you're using `fusion-cli` as a global dependency. Does the same issue happen when you run `yarn fusion build`?

**Comment by chrisdothtml** [comment]
Closing as the scaffold works for me when using the local (not global) `fusion-cli` dep. Let me know if there are any other issues around this
